server:
  # 服务器的HTTP端口，默认为8080
  port: 15432
  servlet:
    # 应用的访问路径
    context-path: /

scheduled:
  neverStop: false  #设置采集永不停止
  task1:
    startTime: "2023-12-25 21:02:00"  #第一个时间段采集sql开始时间
    endTime: "2023-12-25 21:10:00"    #第一个时间段采集sql结束时间
  task2:
    startTime: "2023-12-25 21:12:00"  #第二个时间段采集sql开始时间
    endTime: "2023-12-25 21:20:00"    #第二个时间段采集sql开始时间
  task3:
    startTime: "2023-12-25 21:22:00"  #第三个时间段采集sql开始时间
    endTime: "2023-12-25 21:50:00"    #第三个时间段采集sql开始时间

linux:
  config:
    host: 127.0.0.1    #linux 主机ip
    port: 22               #linux 端口号
    userName: root         #linux 用户名
    linuxSecret : xxxxxx   #linux 登录密码
    pid: 4573                     # 插桩进程 pid
    filePath: /data/test002/           # 采集的sql生成的文件路径

