spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB

server:
  # 服务器的HTTP端口，默认为8080
  port: 7878
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

scheduled:
  neverStop: false
  task1:
    startTime: "2023-11-14 18:52:00"
    endTime: "2023-11-14 18:58:00"
  task2:
    startTime: "2023-11-14 19:00:00"
    endTime: "2023-11-14 19:20:00"
  task3:
    startTime: "2023-11-14 20:58:02"
    endTime: "2023-11-14 21:24:02"

linux:
  config:
    host: 47.109.88.78    #linux 主机ip
    port: 22               #linux 端口号
    userName: root         #linux 用户名
    linuxSecret: Huawei@123   #linux 登录密码
    uploadPath: /usr/local/dynamic  # 插桩文件上传路径
    pid: 21798                      # 插桩进程 pid

file:
  downloadPathSql: /usr/local/collect/collection.sql
  downloadPathStack: /usr/local/collect/stack.txt

dynamic:
  insertion:
    agentName: agent.jar
    attachName: attach.jar
    environment: source /etc/profile
    prefix: java -jar
    findSql: find / -name dynamic_collection.sql 2>/dev/null
    findStack: find / -name call_stack.txt 2>/dev/null
    resourcePath: stake/
