spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 100MB
      # 设置总上传的文件大小
      max-request-size: 200MB

server:
  # 服务器的HTTP端口，默认为8080
  port: 1001
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

scheduled:
  neverStop: false
  task1:
    startTime: "2023-11-28 20:22:00"
    endTime: "2023-11-28 20:40:00"
  task2:
    startTime: "2024-11-14 19:00:00"
    endTime: "2024-11-14 19:20:00"
  task3:
    startTime: "2024-11-14 20:58:02"
    endTime: "2024-11-14 21:24:02"

linux:
  config:
    host: 47.109.88.78    #linux 主机ip
    port: 22               #linux 端口号
    userName: root         #linux 用户名
    linuxSecret: Huawei@123   #linux 登录密码
    pid: 16488                     # 插桩进程 pid
